sudo: false

language: node_js
node_js:
  - 10

branches:
  provider: heroku
  app: datalyzer-web
  api_key:
    secure: 884ecba9-5174-4134-bcc1-5ea937711c87
  only:
    - develop

script:
  - npm run test
  - npm run build
