// Providers
export const DB_CONNECTION = 'DATABASE_CONNECTION';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_TYPE_REPOSITORY = 'USER_TYPE_REPOSITORY';

export const CONNECTION_REPOSITORY = 'CONNECTION_REPOSITORY';
export const CONNECTION_TYPE_REPOSITORY = 'CONNECTION_TYPE_REPOSITORY';

export const MODEL_REPOSITORY = 'MODEL_REPOSITORY';
